function [AVG_targetsource, AVG_featsource, AVG_feattarget] = analyze_average_subject(nifti_image_avg, sourceRegionMask, targetRegionMask, feat_all, winkler, nb_perm, extra)
    msg = compose(" extracting regions...");
    fprintf(msg);
    cr1 = repmat('\b', 1, strlength(msg));
    sourceRoiAVG = extract2DRois(find(sourceRegionMask), nifti_image_avg);
    targetRoiAVG = extract2DRois(find(targetRegionMask), nifti_image_avg);

    % canonical correaltion between the two regions
    msg = compose(" computing cca between regions...");
    fprintf(cr1 + msg);
    cr1 = repmat('\b', 1, strlength(msg));
    permSchema = initPermutationTests(nb_perm, size(sourceRoiAVG,1));
    warning('off');
    % [A_AVG, B_AVG, raw_corr_AVG, U_AVG, V_AVG, stats] = canoncorr(targetRoiAVG, sourceRoiAVG);
    if ~winkler
        [p, r, A, B, U, V] = my_permcca(targetRoiAVG, sourceRoiAVG, permSchema);
    else
        [p, r, A, B, U, V] = permcca(targetRoiAVG, sourceRoiAVG, permSchema);
    end
    AVG_targetsource = struct('p', p,...
        'r', r, ...
        'A', A,...
        'B', B,...
        'U', U, ...
        'V', V, ...
        'winkler', winkler);
    % canonical correaltion between regions and features
    AVG_featsource = nan; AVG_feattarget = nan; 
    if extra
        msg = compose(" computing cca between features and regions...");
        fprintf(cr1 + msg);
        cr1 = repmat('\b', 1, strlength(msg));
        if ~winkler
            [pfwer_Source_AVG, rMusSource_AVG, A_Source_AVG, B_Source_AVG, U_Source_AVG, V_Source_AVG] = my_permcca(feat_all, sourceRoiAVG, permSchema);
            [pfwer_Target_AVG, rMusTarget_AVG, A_Target_AVG, B_Target_AVG, U_Target_AVG, V_Target_AVG] = my_permcca(feat_all, targetRoiAVG, permSchema);
        else
            [pfwer_Target_AVG, rMusTarget_AVG ,A_Target_AVG, B_Target_AVG, U_Target_AVG, V_Target_AVG] = permcca(feat_all, targetRoiAVG, permSchema);
        end
        AVG_featsource = struct('pfwer_Source_AVG',pfwer_Source_AVG,...
            'rMusSource_AVG', rMusSource_AVG,...
            'A_Source_AVG', A_Source_AVG, ...
            'B_Source_AVG', B_Source_AVG,...
            'U_Source_AVG', U_Source_AVG, ...
            'V_Source_AVG', V_Source_AVG, ...
            'winkler', winkler);
        AVG_feattarget = struct('pfwer_Target_AVG',pfwer_Target_AVG,...
            'rMusTarget_AVG', rMusTarget_AVG,...
            'A_Target_AVG', A_Target_AVG, ...
            'B_Target_AVG', B_Target_AVG,...
            'U_Target_AVG', U_Target_AVG, ...
            'V_Target_AVG', V_Target_AVG, ...
            'winkler', winkler);
    end
    fprintf(cr1 + " Done!");
end