function [pval_full, corr_full, ...
            pval_res, corr_res, ...
            source_canvars_mean_activity, ...
            target_canvars_mean_activity] = apply_cca_on_subj(paths_nifti, output_folder, sourceRegionMask, targetRegionMask, ...
                AVG_targetsource, nb_perm, feat_all)
    cr1 = ""; cr0 = "";
    for sub_i=1:length(paths_nifti)
        msg = compose("%s subject n. %d/%d ", string(duration(0, 0, toc)), sub_i, length(paths_nifti));
        fprintf("" + cr1 + cr0 + msg);
        cr0 = repmat('\b', 1, strlength(msg));
    
        pathnifti = paths_nifti{sub_i};
        msg = compose(" ...loading image");
        fprintf( msg);
        cr1 = repmat('\b', 1, strlength(msg));
        nifti_image = niftiread(pathnifti);
        nifti_image = zscore(nifti_image, 0, 4);
    
        msg = compose(" ...applying cca coeff");
        fprintf( cr1 + msg);
        cr1 = repmat('\b', 1, strlength(msg));
        [pval_full{sub_i}, corr_full{sub_i}, ...
            pval_res{sub_i}, corr_res{sub_i}, ...
            source_canvars_mean_activity{sub_i}, ...
            target_canvars_mean_activity{sub_i}] = gli2subjects(...
                nifti_image, sourceRegionMask, targetRegionMask, ...
                AVG_targetsource, nb_perm, feat_all);
    end
    save(fullfile(output_folder, 'corr_pval_subj'), ...
        'pval_full', 'corr_full', 'pval_res', 'corr_res', ...
        'source_canvars_mean_activity', 'target_canvars_mean_activity');
end