function masks = get_masks(atlas_path, deriv_path, roi1_pattern, cort_labels, roi2_pattern, subcort_labels, ...
        hcp_labels, cort_atlas_path, subcort_atlas_path, hcp_atlas_path, opts)
    [roi1_id, roi1_label, roi2_id, roi2_label] = loadAndDisplayROIs(...
        atlas_path, roi1_pattern, cort_labels, roi2_pattern, subcort_labels, hcp_labels);
    
    [masks, ~] = createMasks( ...
        roi1_id, roi2_id, atlas_path, deriv_path, ...
        cort_atlas_path, subcort_atlas_path, hcp_atlas_path, opts.smooth_regions_padding, ...
        opts.smooth_cortex_padding, roi1_label, roi2_label);
    
    masks.roi1_label_id = roi1_id;
    masks.roi2_label_id = roi2_id;
end
