% --- Helper function to initialize parameters ---
function params = initializeParams(opts, roi1_pattern, roi2_pattern, output_folder)
    global feature_list;

    % Initialize parameters struct
    params = struct( ...
        'nb_perm_step1', opts.nb_perm_step1, ...
        'smooth_regions_padding', opts.smooth_regions_padding, ...
        'smooth_cortex_padding', opts.smooth_cortex_padding, ...
        'roi1_pattern', roi1_pattern, ...
        'roi2_pattern', roi2_pattern, ...
        'extra', opts.extra, ...
        'radius', opts.radius, ...
        'padding', opts.padding, ...
        'pVxIn', opts.pVxIn, ...
        'target_model', opts.target_model, ...
        'changed_features', false, ...
        'channel', opts.channel ...
    );

    % Extract music features for both channels
    % Assuming feature_list and other variables are defined globally or within params
    params = get_music_features(params, feature_list, 20);

    param_file = fullfile(output_folder, 'params');
    save(param_file, 'params');
    fprintf("Saved params.mat to %s\n", param_file);

end
